[package]
name = "lost-cities"
version = "0.1.0"
authors = ["Michael Alexander"]

[dependencies]
rand = "^0.3.14"
brdgme-game = { path = "../game" }
brdgme-color = { path = "../color" }
brdgme-markup = { path = "../markup" }
brdgme-cmd = { path = "../cmd" }
combine = "^2.0.0-beta2"
serde = "^0.8.6"
serde_macros = "^0.8.6"
