[package]
name = "lost-cities"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
rand = "^0.3.14"
brdgme-game = { path = "../game" }
brdgme-color = { path = "../color" }
brdgme-markup = { path = "../markup" }
brdgme-cmd = { path = "../cmd" }
combine = { git = "https://github.com/Marwes/combine.git" }
serde = "^0.8.6"
serde_macros = "^0.8.6"

[replace]
"aster:0.26.1" = { git = "https://github.com/jchlapinski/aster" }
