[package]
name = "lost-cities"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { path = "../std" }
brdgme-game = { path = "../game" }
brdgme-color = { path = "../color" }
brdgme-markup = { path = "../markup" }
rand = "*"
combine = "*"
serde = "*"
serde_derive = "*"
