[package]
name = "lost-cities"
version = "0.1.0"
authors = ["Michael Alexander"]

[dependencies]
rand = "^0.3.14"
brdgme-game = { path = "../game" }
brdgme-color = { path = "../color" }
brdgme-markup = { path = "../markup" }
peg = "^0.3.0"
